"""Export a learned notch configuration back into faust-icc.

The point of this file: the neural policy is a *design tool*, not the
deployment target. faust-icc stays the real-time implementation. This
writes a preset that ``lib/icc.lib`` can include, closing the loop between
the two repositories.
"""

from __future__ import annotations

import torch

HEADER = """// Generated by StabilityGAN -- do not edit by hand.
// Learned notch preset for faust-icc (https://github.com/Dhwaani/In-CarCommunication)
//
// Usage in a FAUST design:
//   import("icc.lib");
//   import("learned_preset.dsp");
//   process = ic.gainCeiling(msg, margin, requested) : learnedNotchBank;
"""


def export_preset(freq: torch.Tensor, depth: torch.Tensor, sample_rate: int, path: str) -> str:
    """Write a .dsp preset. ``freq``/``depth`` are (K,) tensors."""
    nyq = sample_rate / 2.0
    freqs_hz = (freq.detach().cpu() * nyq).tolist()
    depths = depth.detach().cpu().tolist()

    lines = [HEADER, 'import("stdfaust.lib");', 'ic = library("icc.lib");', ""]
    lines.append(f"// sample rate at training time: {sample_rate} Hz")
    lines.append(f"nSlots = {len(freqs_hz)};")
    lines.append("")
    for i, (f, d) in enumerate(zip(freqs_hz, depths)):
        lines.append(f"learnedFreq{i} = {f:.2f};   // Hz")
        lines.append(f"learnedDepth{i} = {d:.4f};")
    lines.append("")
    chain = " : ".join(
        f"fi.notchw(learnedFreq{i} * 0.05, learnedFreq{i}) * learnedDepth{i} "
        f"+ _ * (1 - learnedDepth{i})"
        for i in range(len(freqs_hz))
    )
    lines.append(f"learnedNotchBank = {chain};")
    lines.append("")

    text = "\n".join(lines)
    with open(path, "w") as fh:
        fh.write(text)
    return text
